name: "Export Workflow Run Logs"
description: "Uses the GitHub API to download workflow logs and upload them to the target destination."

inputs:
  repo-token:
    description: "GitHub API token to make requests with."
    required: true

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.repo-token }}
