name: "Export Workflow Run Logs"
description: "An action to automatically export GitHub Actions Workflow run logs to popular cloud storage solutions like S3." # NOTE: This field has a 125 character limit

branding:
  icon: "save"
  color: "gray-dark"

inputs:
  repo-token:
    description: "GitHub API token to make requests with."
    required: true
  run-id:
    description: "The workflow run ID to export logs for"
    required: true
  destination:
    description: "The service to export workflow logs to"
    required: true
  aws-access-key-id:
    description: "AWS Access Key ID. Required if destination is 's3'."
  aws-secret-access-key:
    description: "AWS Secret Access Key. Required if destination is 's3'."
  aws-session-token:
    description: "AWS Session Token. Required if destination is 's3' and if using temporary credentials."
  aws-region:
    description: "AWS Region in which the S3 bucket is located. Required if destination is 's3'."
  s3-bucket-name:
    description: "S3 Bucket to export workflow logs to. Required if destination is 's3'."
  s3-key:
    description: "S3 path to save the workflow logs to. Required if destination is 's3'."
  azure-storage-account-name:
    description: "The Azure storage account name. Required if destination is 'blobstorage'."
  azure-storage-account-key:
    description: "Access key for the storage account. Required if destination is 'blobstorage'."
  container-name:
    description: "Container name to save the workflow logs to. Required if destination is 'blobstorage'."
  blob-name:
    description: "Blob name to save the workflow logs as. Required if destination is 'blobstorage'."
  cloud-storage-bucket-name:
    description: "Cloud Storage Bucket name to save the workflow logs to. Required if destination is 'cloudstorage'."
  cloud-storage-object-name:
    description: "Cloud Storage object name to save the workflow logs as. Required if destination is 'cloudstorage'."

runs:
  using: "docker"
  image: docker://ghcr.io/timorthi/export-workflow-logs:sha-1fdc0e0
  args:
    - --repo-token=${{ inputs.repo-token }}
    - --run-id=${{ inputs.run-id }}
    - --destination=${{ inputs.destination }}
    - --aws-access-key-id=${{ inputs.aws-access-key-id }}
    - --aws-secret-access-key=${{ inputs.aws-secret-access-key }}
    - --aws-session-token=${{ inputs.aws-session-token }}
    - --aws-region=${{ inputs.aws-region }}
    - --s3-bucket-name=${{ inputs.s3-bucket-name }}
    - --s3-key=${{ inputs.s3-key }}
    - --azure-storage-account-name=${{ inputs.azure-storage-account-name }}
    - --azure-storage-account-key=${{ inputs.azure-storage-account-key }}
    - --container-name=${{ inputs.container-name }}
    - --blob-name=${{ inputs.blob-name }}
    - --cloud-storage-bucket-name=${{ inputs.cloud-storage-bucket-name }}
    - --cloud-storage-object-name=${{ inputs.cloud-storage-object-name }}
